apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dse.fullname" . }}-opsc-admin-pwd-secret
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: dse
    app: {{ template "dse.fullname" . }}-opsc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: dse
type: Opaque
data:
  password: {{ .Values.opscAdminPassword | quote }}
