## dse-opscenter and dse_clsuter_init docker images
imageDSE:
  image: "gcr.io/datastax-public/dse:6.1"
  pullPolicy: IfNotPresent

imageDseOpscenter:
  image: "gcr.io/datastax-public/dse/dse-opscenter-653:6.1"
  pullPolicy: IfNotPresent

imageDseClusterInit:
  image: "gcr.io/datastax-public/dse/dse-cluster-init:6.1"
  pullPolicy: IfNotPresent

imageDseCurl:
  image: "gcr.io/datastax-public/dse-curl:6.1"
  pullPolicy: IfNotPresent

## Default OPSC admin password
opscAdminPassword: ZGF0YXN0YXgxIQ==

## GCE storage configuration for persistent disks
storageClass: fast
diskSize: 60Gi

## Specify a service type
## ref: http://kubernetes.io/docs/user-guide/services/
service:
  type: ClusterIP

## Persist data to a persitent volume
persistence:
  ## cassandra data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  accessMode: ReadWriteOnce

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## Minimum memory for development is 4GB and 2 CPU cores
## Minimum memory for production is 8GB and 4 CPU cores
## ref: http://docs.datastax.com/en/archived/cassandra/2.0/cassandra/architecture/architecturePlanningHardware_c.html
resources:
  dse_requests:
    memory: 4Gi
    cpu: 2
  opsc_requests:
    memory: 4Gi
    cpu: 2

## Change cassandra configuration paramaters below:
## ref: http://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/configCassandra_yaml.html
## Recommended max heap size is 1/2 of system memory
## Recommeneed heap new size is 1/4 of max heap size
## ref: http://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsTuneJVM.html
config:
  cluster_size: 3
  seed_size: 1
  cluster_name: My_Cluster
  num_tokens: 256
  dc_name: DC1
  rack_name: RAC1
  ports:
    cql: 9042
    thrift: 9160
    # If a JVM Agent is in place
    ds_agent: 61621
    opsc_gui_port: 8888
    ds_agent_opsc: 61620
  endpoint_snitch: GossipingPropertyFileSnitch

## Additional pod labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

securityContext:
  fsGroup_dse: 999
  fsGroup_opscenter: 998

podManagementPolicy:
  type: OrderedReady

updateStrategy:
  type: RollingUpdate
